name: Testing
on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3

      - name: load cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/coursier/v1
          key: ${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/build.properties') }}

      - name: test
        run: ./sbtx test
        continue-on-error: true

      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/test-reports/
